name: mystarter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  shared_preferences: ^2.0.13
  http: ^0.13.4
  flutter_svg: ^1.0.3
  shimmer: ^2.0.0
  flutter_spinkit: ^5.1.0
  carousel_slider: ^4.0.0
  get: ^4.6.1
  get_storage: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
#  adaptive_icon_background: "assets/images/bg.png"
#  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
